backend:
  name: git-gateway
  branch: test-branch-2 # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Heading1', name: 'heading1', widget: 'string' }
      - name: meta
        widget: list
        fields:
          - { name: name }
          - { name: content }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          default: '../../assets/img/holaluz-default-image.jpg',
        }
      - {
          label: 'IsImportant',
          name: 'isimportant',
          widget: 'boolean',
          default: false,
        }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'select',
          options:
            ['tramites', 'factura', 'solar', 'gas', 'preguntas-frecuentes'],
        }
      - {
          label: 'Permalink',
          name: 'permalink',
          widget: 'select',
          options:
            [
              '/tramites/:slug',
              '/factura/:slug',
              '/solar/:slug',
              '/gas/:slug',
              '/preguntas-frecuentes/:slug',
            ],
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
